#!/usr/bin/env python

import glob
import h5py
import numpy as np
import healpy
import itertools

types = ['hitmap', 'rcondmap']

STOKES = ['I','Q','U','S1','S2']

for map in ['binmap', 'summap']:
    for S in STOKES:
        types.append('_'.join([map, S]))

for comb in itertools.combinations(STOKES, 2):
    types.append('_'.join(['M',comb[0],comb[1]]))

for type in types:
    print(type)
    s=sorted(glob.glob('%s_*.h5' % type))
    if s:
        cat = np.concatenate([h5py.File(f)['Vector'].value for f in s])
        healpy.write_map(type + ".fits", cat[:-1],nest=True)
    else:
        print('Nothing to do')

