#!/usr/bin/env python

import sys
import glob
import h5py
import numpy as np
import healpy
import itertools

types = ['hitmap', 'rcondmap']

STOKES = ['I','Q','U']

for i in range(1,6+1):
    STOKES.append('S%d' % i)

for map in ['binmap', 'summap']:
    for S in STOKES:
        types.append('_'.join([map, S]))

for comb in itertools.combinations(STOKES, 2):
    types.append('_'.join(['M',comb[0],comb[1]]))

for type in types:
    print(type)
    s=sorted(glob.glob(sys.argv[1] + '/%s_*.h5' % type))
    if s:
        cat = np.concatenate([h5py.File(f)['Vector'].value for f in s])
        healpy.write_map(sys.argv[1] + '/' + type + ".fits", cat[:-1],nest=False)
    else:
        print('Nothing to do')

