#!/usr/bin/env python

import sys
import glob
import h5py
import numpy as np
import healpy
import itertools
import os

dir = sys.argv[1].replace('out','fits')
try:
    os.mkdir(dir)
except:
    pass
types = ['hitmap', 'rcondmap']

STOKES = ['I','Q','U']

for i in range(1,6+1):
    STOKES.append('S%d' % i)

maps = []
for h in range(18, 28+1):
    maps.append('binmap_LFI%dM' % h)

for map in maps:
    for S in STOKES:
        types.append('_'.join([map, S]))

for i in range(len(STOKES)):
    for j in range(i, len(STOKES)):
        types.append('_'.join(['M',STOKES[i], STOKES[j]]))

for type in types:
    print(type)
    s=sorted(glob.glob(sys.argv[1] + '/%s_*.h5' % type))
    if s:
        cat = np.concatenate([h5py.File(f)['Vector'].value for f in s])
        healpy.write_map(dir + '/' + type + ".fits", cat[:-1],nest=True)
    else:
        print('Nothing to do')
